---
- hosts: all
  remote_user: spartan
  become: true
  become_user: root


  tasks:
    # - name: delete docker repo
    #   file:
    #     path: "{{file}}"
    #     state: absent
    #   with_fileglob:
    #     - /etc/yum.repos.d/docker_cc.repo

    - name: install Docker required packages
      yum: name="{{item}}" state=installed
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    
    # Handler showing how to clean yum metadata cache
    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: no

    - name: disable docker repo
      yum_repository:
        name: docker_cc
        state: absent
      notify: yum-clean-metadata

    - name: Install EPEL
      yum: name="{{item}}" state=installed
      with_items:
        - epel-release

    - name: Install docker-engine and pip
      yum: name="{{item}}" state=installed
      with_items:
        - docker
        - python-pip

    - name: Ensure docker-py and docker-compose are installed
      pip: name={{item}}
      with_items:
        - docker-py
        - docker-compose                  

    - name: Start/enable docker service
      service: name=docker enabled=yes state=started

    - name: Create docker user
      user: name=docker group=dockerroot uid=991
