---
- hosts: all
  remote_user: spartan

  tasks:
    - name: Add docker-engine yum repo
      template: src=/etc/semaphore/repository_1/ansible-role-docker-master/templates/docker.repo.j2 dest=/etc/yum.repos.d/docker.repo

    - name: Change docker repo from RHEL to CentOS
      replace:
        dest: /etc/yum.repos.d/docker.repo
        regexp: 'RedHat'
        replace: 'centos'
      when: "{{ ansible_distribution == 'RedHat' }}"

    - name: Install EPEL
      yum: name="{{item}}" state=installed
      with_items:
        - epel-release

    - name: Install docker-engine and pip
      yum: name="{{item}}" state=installed
      with_items:
        - docker
        - python-pip

    - name: Ensure docker-py and docker-compose are installed
      pip: name={{item}}
      with_items:
        - docker-py
        - docker-compose                  

    - name: Start/enable docker service
      service: name=docker enabled=yes state=started

    - name: Create docker user
      user: name=docker group=docker uid=991
